<a href="https://colab.research.google.com/github/ai-technipreneurs/python_course_colab_notebooks/blob/main/06_Lecture06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center>
    <a href="https://aims-senegal.org/" ><img src="images/logoaimssn.jpeg" style="float:left; max-width: 650px; display: inline" alt="AIMS-SN"/> </a>
    </center>



<center>
    
<a href="https://acas-yde.org/" ><img src="images/logo-ACAS.jpg" style="float:right; max-width: 250px; display: inline" alt="ACAS"/></a>
    
</center>


****

# <center> <b> <span style="color:orange;"> Python Proficiency for Scientific Computing and Data Science (PyPro-SCiDaS)  </span> </b></center>

### <center> <b> <span style="color:green;">An Initiation to Programming using Python (Init2Py) </span> </b></center>
    


****

# <center> <b> <span style="color:blue;"> Lecture 6: Numpy </span> </b></center>

<!--NAVIGATION-->
<  [5.Functions, Modules & PAckages](05.Lecture05.ipynb)| [ToC](Index.ipynb) | [7.Matplotlib](07.Lecture07.ipynb)>

****

<img src=" numpy.gif" alt="Vlad's Home Directory" />

[The NumPy Reference](https://docs.scipy.org/doc/numpy/reference/).


### <left> <b> <span style="color:brown;"> Objective: </span> </b></left>

This lecture aims to introduce the core concepts of `NumPy`, a fundamental library for numerical computing in Python. We will explore how to create and manipulate multidimensional arrays, perform vectorized operations, and efficiently handle large datasets. By understanding these tools, you'll gain the ability to perform high-performance numerical computations and build the foundation for scientific computing and data analysis using `NumPy`.
****

## What is NumPy?


> **NumPy (Numerical Python)** is the core library for scientific computing in Python, that provide high-performance vector, matrix, and higher-dimensional data structures for Python. It is implemented in ``C`` and ``Fortran``. so when calculations are vectorized (formulated with vectors and matrices), the performance is very good. It provides a high-performance multidimensional array object, and tools for working with these arrays.


> This library can be used for different functions in **Linear algebra, Matrix computations, Fourier Transforms**. Alongside Numpy is most suitable for performing basic numerical computations such as *mean, median, range*, etc.

> It is an open source module of Python which provides fast mathematical computation on arrays and matrices. Since, arrays and matrices are an essential part of the Machine Learning ecosystem.

> ``Machine learning`` uses vectors, and in that regard, Numpy can be used in all common classes of problem in Machine Learning. Example: **Classification, Regressoin, Clustering** etc.



<img src="object.png" alt="Vlad's Home Directory" />

## NumPy arrays

At the core of the NumPy package, is the ``ndarray`` object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance.

  
  
  A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the *rank* of the array; the *shape* of an array is a tuple of integers giving the size of the array along each dimension.
  
  
  <img src=" 1d_array.png" alt="Vlad's Home Directory" />
  
Data manipulation in Python is nearly synonymous with NumPy array manipulation: even newer tools like Pandas are built around the NumPy array. This section will present several examples of using NumPy array manipulation to access data and subarrays, and to split, reshape, and join the arrays.   


There are a number of ways to initialize new numpy arrays, for example from

* a Python list or tuples;
* using functions that are dedicated to generating numpy arrays, such as arange, linspace, etc.;
* reading data from files.

### To use numpy you need to import the module

**Import conventions** : The recommended convention to import numpy is:

In [ ]:
import numpy as np

### From lists
For example, to create new vector and matrix arrays from Python lists we can use the ``np.array`` function.

In [38]:
# a vector: the argument to the array function is a Python list
v = np.array([1,2,3,4])
print(v)

[1 2 3 4]


In [40]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [42]:
b = np.array([[1,2,3],[4,5,6]]) 
c =  np.array([[1,2,3],[4,5,6],[7,8,9]]) 
print(c)
print(c.shape)
print(b) # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"
print(b[1, 1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
[[1 2 3]
 [4 5 6]]
(2, 3)
1 2 4
5


### Numpy also provides many functions to create arrays:

In [44]:
import numpy as np


print("-----------------------------------------------------------------------")

print("Evenly spaced: \n")

a1 = np.arange(10) # 0 .. n-1  (!). Evenly spaced.
print(a1)

print("\n")

b1 = np.arange(1, 9, 2) # start, end (exclusive), step.
print(b1)


print("=========================================================================")

print("Spaced by number of points: \n")


c1 = np.linspace(0, 1, 9)   # start, end, num-points
print(c1)


print("\n")

d1 = np.linspace(0, 1, 5, endpoint=False)
print(d1)



print("=========================================================================")
print("Common arrays: \n")


a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"
print("\n")

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

print("\n")

c = np.full((2,2), 8)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"
print("\n")

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"
print("\n")

e = np.random.random((2,2))  # Create an array filled with random values
print("E=",e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"





-----------------------------------------------------------------------
Evenly spaced: 

[0 1 2 3 4 5 6 7 8 9]


[1 3 5 7]
Spaced by number of points: 

[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.   ]


[0.  0.2 0.4 0.6 0.8]
Common arrays: 

[[0. 0.]
 [0. 0.]]


[[1. 1.]]


[[8 8]
 [8 8]]


[[1. 0.]
 [0. 1.]]


E= [[0.61426177 0.75767068]
 [0.03291436 0.85242577]]


You can read about other methods of array creation [in the documentation](https://docs.scipy.org/doc/numpy/user/basics.creation.html#arrays-creation).

* * * *
Exercise: **Creating arrays using functions**

> Experiment with arange, linspace, ones, zeros, eye and diag.
    Create different kinds of arrays with random numbers.
    Try setting the seed before creating an array with random values.
    Look at the function np.empty. What does it do? When might this be useful?

* * * *

### NumPy Array Attributes

Each array has attributes ``ndim`` (the number of dimensions), ``shape`` (the size of each dimension), and ``size`` (the total size of the array):

In [46]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array


In [48]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


### Basic data types

Different data-types allow us to store data more compactly in memory, but most of the time we simply work with floating point numbers. Note that, in the example above, NumPy auto-detects the data-type from the input.

In [50]:
a = np.array([1, 2, 3])
print(a.dtype)


b = np.array([1., 2., 3.])
print(b.dtype)


int32
float64


In [ ]:
You can explicitly specify which data-type you want:

In [52]:
c = np.array([1, 2, 3], dtype=np.float16)
print(c.dtype)

float16


Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is a more example:

In [54]:
import numpy as np

x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"


int32
float64
int64


You can read all about numpy datatypes [in the documentation](https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

### **What is the default data type ?**

There are also other types:
    
 <img src="types.png" alt="Vlad's Home Directory" />
    

## Array Indexing: Accessing Elements/Subarrays


Numpy offers several ways to index into arrays.

**Slicing**: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:



In [56]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

print(a)

print('--------------------------------------------------------------------------')

print(b)

print('--------------------------------------------------------------------------')


# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"

print('--------------------------------------------------------------------------')

b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
--------------------------------------------------------------------------
[[2 3]
 [6 7]]
--------------------------------------------------------------------------
2
--------------------------------------------------------------------------
77


You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array.

In [58]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"

print('--------------------------------------------------------------------------')


print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"

print('--------------------------------------------------------------------------')

print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"


[5 6 7 8] (4,)
--------------------------------------------------------------------------
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
--------------------------------------------------------------------------
[[ 2]
 [ 6]
 [10]] (3, 1)


### Reshaping of Arrays

Another useful type of operation is reshaping of arrays. The most flexible way of doing this is with the ``reshape`` method. For example, if you want to put the numbers 1 through 9 in a $3 \times 3$ grid, you can do the following:

In [60]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Note that for this to work, the size of the initial array must match the size of the reshaped array. Tyr a few examples that you will create.

### Fancy indexing

Fancy indexing is the name for when an array or a list is used in-place of an index:

In [62]:
twenty = (np.arange(4 * 5)).reshape(4, 5)
twenty

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [64]:
row_indices = [1, 2, 3]
twenty[row_indices]


array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [66]:
col_indices = [1, 2, -1] # remember, index -1 means the last element
twenty[row_indices, col_indices]

array([ 6, 12, 19])



We can also use index **masks**:

    If the index mask is a NumPy array of data type bool, then an element is selected (True) or not (False) depending on the value of the index mask at the position of each element



In [68]:
# 1D array of random integers
# get 10 integers from 0 to 23

num_samples = 10
integers = np.random.randint(23, size=num_samples)
integers

array([15, 20,  3, 12,  4, 20,  8, 14, 15, 20])

In [70]:
# mask has to be of the same shape as the array to be indexed; else IndexError would be thrown
# mask for indexing alternate elements in the array
row_mask = np.array([True, False, True, False, True, False, True, False, True, False])

integers[row_mask]

array([15,  3,  4,  8, 15])



This feature is very useful to conditionally select elements from an array, using for example comparison operators:


In [72]:
range_arr = np.arange(0, 10, 0.5)
range_arr

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [74]:
mask = (range_arr > 5) * (range_arr < 7.5)
mask
# What is happenning here?

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False])

In [76]:
range_arr[mask]

array([5.5, 6. , 6.5, 7. ])

* * * *
### Exercise:
 > Investigate the **Concatenation, Splitting, Copies,repeat, tile, vstack, hstack**  functions for numpy arrays.

 > Investigate [Views versus copies in NumPy](https://scipy-cookbook.readthedocs.io/items/ViewsVsCopies.html)



* * * *

## Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [78]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))


[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


We instead use the ``dot`` function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. ``dot`` is available both as a function in the numpy module and as an instance method of array objects:

In [80]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))


219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Numpy provides many useful functions for performing computations on arrays; one of the most useful is ``sum``

In [82]:
import numpy as np

x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"


10
[4 6]
[3 7]


You can find the full list of mathematical functions provided by numpy [in the documentation](https://docs.scipy.org/doc/numpy/reference/routines.math.html).

## Vectorizing functions

As mentioned several times by now, to get good performance we should always try to avoid looping over elements in our vectors and matrices, and instead use vectorized algorithms. The first step in converting a scalar algorithm to a vectorized algorithm is to make sure that the functions we write work with vector inputs.

In [84]:
def Theta(x):
    """
    scalar implementation of the Heaviside step function.
    """
    if x >= 0:
        return 1
    else:
        return 0

In [86]:
v1 = np.array([-3,-2,-1,0,1,2,3])
Theta(v1)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()



That didn't work because we didn't write the function Theta so that it can handle a vector input...

To get a vectorized version of Theta we can use the Numpy function vectorize. In many cases it can automatically vectorize a function:


In [88]:
Theta_vec = np.vectorize(Theta)
Theta_vec(v1)

array([0, 0, 0, 1, 1, 1, 1])

On the Other Hand (OTHO), we can also implement the function to accept a vector input from the beginning (requires more effort but might give better performance):

In [90]:
def Theta(x):
    """
    Vector-aware implementation of the Heaviside step function.
    """
    return 1 * (x >= 0)

In [92]:
Theta(v1)

array([0, 0, 0, 1, 1, 1, 1])

In [94]:
# it even works with scalar input
Theta(-1.2), Theta(2.6)

(0, 1)

Numpy provides many more functions for manipulating arrays; you can see the full list [in the documentation](https://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html).

## Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

<img src="broad.png" alt="Vlad's Home Directory" />

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [96]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


This works; however when the matrix ``x`` is very large, computing an explicit loop in Python could be slow. Note that adding the vector ``v ``to each row of the matrix ``x`` is equivalent to forming a matrix ``vv`` by stacking multiple copies of ``v`` vertically, then performing elementwise summation of ``x`` and ``vv``. We could implement this approach like this:

In [98]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)                 # Prints "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
y = x + vv  # Add x and vv elementwise
print(y)  # Prints "[[ 2  2  4
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"


[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

In [100]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


The line ``y = x + v`` works even though ``x`` has shape **(4, 3)** and ``v`` has shape **(3,)** due to broadcasting; this line works as if ``v`` actually had shape **(4, 3)**, where each row was a copy of ``v``, and the sum was performed elementwise.

* * * *

Broadcasting two arrays together follows these rules:


1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.

2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
    
3. The arrays can be broadcast together if they are compatible in all dimensions.
    
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
    
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension


If this explanation does not make sense, try reading the explanation from the [documentation](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)
Functions that support broadcasting are known as universal functions. You can find the list of all universal functions [in the documentation](https://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

In [ ]:
Here are some applications of broadcasting:

In [102]:
import numpy as np

# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(x + v)

# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)


[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]


In [110]:
#Challenge 2
#Question 7
# program that accepts two numbers, X and Y, as input and generates a 2-dimensional list. 
#such that The value at the i-th row and j-th column is the product of i and j.
import numpy as np
X = int(input("Enter the first number"))
Y = int(input("Enter the second number"))
u_list = [[i * j for j in range(Y)] for i in range(X)]
# Printing the resulting list
print(u_list)

  

Enter the first number 2
Enter the second number 5


[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4]]


In [112]:
#Task 4
#program that reads a series of comma-separated numbers from the console, 
#then generates and prints both a list and a tuple containing those numbers. 
# Read the input from the console
input_numbers = input("Enter a series of comma-separated numbers: ")
numbers_list = input_numbers.split(',')
numbers_tuple = tuple(numbers_list)

# Printin the list and tuple
print(numbers_list)
print(numbers_tuple)


Enter a series of comma-separated numbers:  1,2,3,4,5,6,7,8,9,10


['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']
('1', '2', '3', '4', '5', '6', '7', '8', '9', '10')


In [116]:
#Question 6
#Write a program that calculates and prints values based on the formula: [ Q = \sqrt{\frac{2 \times C \times D}{H}} ]
import math

# Fixing the constants C anf H
C = 50
H = 30
d_values = input("Enter comma-separated values for D: ").split(',')
q_values = [int(math.sqrt((2 * C * int(d)) / H)) for d in d_values]
result_list = ",".join(map(str, q_values))

# Printing the final list 
print(result_list)


Enter comma-separated values for D:  100,150,180


18,22,24


In [9]:
import math
#Question 21
# A robot moving on a grid starting from the origin
x, y = 0, 0

# Listing all possible moves
moves = [("UP", 5),("DOWN", 3),("LEFT", 3),("RIGHT", 2)]
for direction, steps in moves:
    if direction == "UP":
        y += steps
    elif direction == "DOWN":
        y -= steps
    elif direction == "LEFT":
        x -= steps
    elif direction == "RIGHT":
        x += steps

# Calculating Euclidean distance from the origin (0, 0) 
distance = math.sqrt(x**2 + y**2)

# Printing the nearest integer of the distance
print(round(distance))


2


In [11]:
#Question 21
#Create a program that sorts a list of (name, age, height) tuples tuples based on the following priority: Name (alphabetically)
#Age (numerically) Height (numerically)

data = [("Tom", 19, 80),("John", 20, 90),("Jony", 17, 91),("Jony", 17, 93),("Json", 21, 85)]

# using the .sort method to Sort the list in place by Name, Age, and Height
data.sort(key=lambda x: (x[0], x[1], x[2]))

# Finally, we print the sorted list
print(data)


[('John', 20, 90), ('Jony', 17, 91), ('Jony', 17, 93), ('Json', 21, 85), ('Tom', 19, 80)]


In [15]:
#Question 17
#Program to calcualte the net amount in a bank account based on a transaction log input. 

net_amount = 0

transactions = [ "D 300", "D 300", "W 200", "D 100"]
for transaction in transactions:
    type, amount = transaction.split()
    amount = int(amount)
    if type == 'D':
        net_amount = net_amount + amount  
    elif type == 'W':
        net_amount = net_amount - amount 
print(net_amount)


500


In [17]:
#Question 16
#Program that uses a list comprehension to generate a list of squares for each odd number in a given sequence of comma-separated values.
input_sequence = "1,2,3,4,5,6,7,8,9"

# First we convert the input sequence to a list of integers
numbers = list(map(int, input_sequence.split(',')))

# Using list comprehension we get the squares of odd numbers
squares_of_odds = [x**2 for x in numbers if x % 2 != 0]

# FInally we convert the result back to a comma-separated string and print
print(",".join(map(str, squares_of_odds)))


1,9,25,49,81


In [25]:
#Question 15
#Program that calculates the value of a + aa + aaa + aaaa given a digit as the value of a.

a = input("Enter a single digit: ")
term1 = int(a)
term2 = int(a * 2)
term3 = int(a * 3)
term4 = int(a * 4)
sum_expresssion = term1 + term2 + term3 + term4


print(sum_expresssion)


Enter a single digit:  5


6170


In [27]:
#Question 14
#Program that counts and prints the number of uppercase and lowercase letters in a given sentence.

user_sentence = input("Enter a sentence: ")
uppercase_count = 0
lowercase_count = 0
for char in user_sentence:
    if char.isupper():
        uppercase_count = uppercase_count + 1
    elif char.islower():
        lowercase_count = lowercase_count + 1

print("UPPER CASE LETTERS ARE: ", uppercase_count)
print("LOWER CASE LETTERS ARE: ", lowercase_count)


Enter a sentence:  Hello my name is Evariste


UPPER CASE LETTERS ARE:  2
LOWER CASE LETTERS ARE:  19


In [31]:
#Question 12
#Program that finds all numbers between 1000 and 3000 (inclusive) where each digit is an even number. 

even_digit_numbers = []
for num in range(1000, 3001):
    num_str = str(num)
    if all(int(digit) % 2 == 0 for digit in num_str):
        even_digit_numbers.append(num_str)

print(",".join(even_digit_numbers))


2000,2002,2004,2006,2008,2020,2022,2024,2026,2028,2040,2042,2044,2046,2048,2060,2062,2064,2066,2068,2080,2082,2084,2086,2088,2200,2202,2204,2206,2208,2220,2222,2224,2226,2228,2240,2242,2244,2246,2248,2260,2262,2264,2266,2268,2280,2282,2284,2286,2288,2400,2402,2404,2406,2408,2420,2422,2424,2426,2428,2440,2442,2444,2446,2448,2460,2462,2464,2466,2468,2480,2482,2484,2486,2488,2600,2602,2604,2606,2608,2620,2622,2624,2626,2628,2640,2642,2644,2646,2648,2660,2662,2664,2666,2668,2680,2682,2684,2686,2688,2800,2802,2804,2806,2808,2820,2822,2824,2826,2828,2840,2842,2844,2846,2848,2860,2862,2864,2866,2868,2880,2882,2884,2886,2888


In [33]:
#Light Practical exercise 
#Execercise 1
#Numpy array of integer from 1 to 10
import numpy as np

array = np.arange(1, 11)
print(array)


[ 1  2  3  4  5  6  7  8  9 10]


In [35]:
#Exercise 2
# 3x3 array with zeroes
import numpy as np

array = np.zeros((3, 3))
print(array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [37]:
#Exercise 3
#NumPy array of 10 evenly spaced numbers between 0 and 5.
import numpy as np

array = np.linspace(0, 5, 10)
print(array)


[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [45]:
#Exercise 4
# 5x5 identity matrix
import numpy as np

array = np.eye(5)
print(array)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [47]:
#exercisre 5
#4x4 matrix with random number between 0 and 1
import numpy as np

matrix = np.random.rand(4, 4)
print(matrix)


[[0.26924016 0.12951215 0.71062267 0.80974927]
 [0.46817796 0.87244914 0.34347186 0.64152077]
 [0.18495849 0.86996242 0.11691778 0.36541952]
 [0.72810033 0.04443413 0.52473494 0.99242574]]


In [49]:
#Exercise 6
#Shape of numpy array
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6]])
shape = array.shape
print("The shape of the given array is",shape)


The shape of the given array is (2, 3)


In [55]:
#Exercise 7
#Reshaping the 1D array to a 4x4 array
import numpy as np

array_1d = np.arange(16)  
print(array_1d)
print("==================================================")
matrix_4x4 = array_1d.reshape((4, 4))
print(matrix_4x4)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [57]:
#Exercise 8
#getting the data tyoes of the elements in the numpy array
import numpy as np
array = np.array([1, 2, 3, 4, 5])
# to get the data type of the elements in the array we as follows
data_type = array.dtype
print(data_type)


int32


In [61]:
#Exercise 9
# Creating a NumPy array of integers from 1 to 100
import numpy as np

user_array = np.arange(1, 101)
even_numbers = user_array[user_array % 2 == 0]
print(even_numbers)


[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [63]:
#Exercise 10
#6x6 numpy array of random number between 10 and 50
import numpy as np
matrix_6x6 = np.random.randint(10, 51, size=(6, 6))
print(matrix_6x6)


[[47 19 28 37 30 44]
 [37 49 27 19 19 13]
 [31 38 16 24 34 19]
 [18 18 10 35 32 26]
 [23 40 28 36 40 28]
 [36 35 13 50 11 49]]


In [65]:
#Exercise 11
#Slicing a numpy array
import numpy as np
matrix = np.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15],
                   [16, 17, 18, 19, 20],
                   [21, 22, 23, 24, 25]])

# Slicing the matrix in oder to extract a submatrix (for example, rows 1 to 3 and columns 1 to 4)
submatrix = matrix[1:4, 1:4]
print("Original Matrix is:")
print(matrix)
print("\n Sliced Submatrix is:")
print(submatrix)


Original Matrix is:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

 Sliced Submatrix is:
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [67]:
#Exercise 12
#Sum of element in numpy array
import numpy as np
array = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
total_sum = np.sum(array)

print("The sum of all elements in the array is :", total_sum)


The sum of all elements in the array is : 45


In [69]:
#Exercise 13
#Mean, median and standard deviation of elements in a numpy array 
import numpy as np
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mean_value = np.mean(array)
median_value = np.median(array)
std_deviation = np.std(array)

print("The mean is:", mean_value)
print("The median is:", median_value)
print("The standard Deviation is:", std_deviation)



The mean is: 5.5
The median is: 5.5
The standard Deviation is: 2.8722813232690143


In [71]:
#Exercise 14
#Max and Min element in a numoy array
import numpy as np

array = np.array([10, 15, 3, 7, 22, 8, 1])
max_value = np.max(array)
min_value = np.min(array)
print("The maximum Value is:", max_value)
print("The minimum Value is:", min_value)


The maximum Value is: 22
The minimum Value is: 1


In [73]:
#Exercise 15
# NumPy array of 20 random integers and find the index of the maximum value.
import numpy as np

array = np.random.randint(0, 100, size=20)
max_index = np.argmax(array)

print("The given array is:", array)
print("The Index of Maximum Value is:", max_index)


The given array is: [50 94 21 46  8 78 24 70 11 56 32 80 48 58 49 16 13 21  3 11]
The Index of Maximum Value is: 1


****

<!--NAVIGATION-->
<  [5.Functions, Modules & PAckages](05.Lecture05.ipynb)| [ToC](Index.ipynb) | [7.Matplotlib](07.Lecture07.ipynb)>

****